# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2017.2.3\bin\cmake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\natshez\Desktop\freshPull\BarrenLands

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\natshez\Desktop\freshPull\BarrenLands

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\Program Files\JetBrains\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\JetBrains\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\natshez\Desktop\freshPull\BarrenLands\CMakeFiles C:\Users\natshez\Desktop\freshPull\BarrenLands\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\natshez\Desktop\freshPull\BarrenLands\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glimac

# Build rule for target.
glimac: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 glimac
.PHONY : glimac

# fast build rule for target.
glimac/fast:
	$(MAKE) -f glimac\CMakeFiles\glimac.dir\build.make glimac/CMakeFiles/glimac.dir/build
.PHONY : glimac/fast

#=============================================================================
# Target rules for targets named glcustom

# Build rule for target.
glcustom: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 glcustom
.PHONY : glcustom

# fast build rule for target.
glcustom/fast:
	$(MAKE) -f glcustom\CMakeFiles\glcustom.dir\build.make glcustom/CMakeFiles/glcustom.dir/build
.PHONY : glcustom/fast

#=============================================================================
# Target rules for targets named fastnoise

# Build rule for target.
fastnoise: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 fastnoise
.PHONY : fastnoise

# fast build rule for target.
fastnoise/fast:
	$(MAKE) -f fastnoise\CMakeFiles\fastnoise.dir\build.make fastnoise/CMakeFiles/fastnoise.dir/build
.PHONY : fastnoise/fast

#=============================================================================
# Target rules for targets named barrenLands

# Build rule for target.
barrenLands: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 barrenLands
.PHONY : barrenLands

# fast build rule for target.
barrenLands/fast:
	$(MAKE) -f barrenLands\CMakeFiles\barrenLands.dir\build.make barrenLands/CMakeFiles/barrenLands.dir/build
.PHONY : barrenLands/fast

#=============================================================================
# Target rules for targets named TEST_createMapBiomeTexture

# Build rule for target.
TEST_createMapBiomeTexture: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 TEST_createMapBiomeTexture
.PHONY : TEST_createMapBiomeTexture

# fast build rule for target.
TEST_createMapBiomeTexture/fast:
	$(MAKE) -f tests\CMakeFiles\TEST_createMapBiomeTexture.dir\build.make tests/CMakeFiles/TEST_createMapBiomeTexture.dir/build
.PHONY : TEST_createMapBiomeTexture/fast

#=============================================================================
# Target rules for targets named TEST_lightNormal

# Build rule for target.
TEST_lightNormal: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 TEST_lightNormal
.PHONY : TEST_lightNormal

# fast build rule for target.
TEST_lightNormal/fast:
	$(MAKE) -f tests\CMakeFiles\TEST_lightNormal.dir\build.make tests/CMakeFiles/TEST_lightNormal.dir/build
.PHONY : TEST_lightNormal/fast

#=============================================================================
# Target rules for targets named TEST_lightWithCam

# Build rule for target.
TEST_lightWithCam: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 TEST_lightWithCam
.PHONY : TEST_lightWithCam

# fast build rule for target.
TEST_lightWithCam/fast:
	$(MAKE) -f tests\CMakeFiles\TEST_lightWithCam.dir\build.make tests/CMakeFiles/TEST_lightWithCam.dir/build
.PHONY : TEST_lightWithCam/fast

#=============================================================================
# Target rules for targets named TEST_moveCamera

# Build rule for target.
TEST_moveCamera: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 TEST_moveCamera
.PHONY : TEST_moveCamera

# fast build rule for target.
TEST_moveCamera/fast:
	$(MAKE) -f tests\CMakeFiles\TEST_moveCamera.dir\build.make tests/CMakeFiles/TEST_moveCamera.dir/build
.PHONY : TEST_moveCamera/fast

#=============================================================================
# Target rules for targets named TEST_reloadShaders

# Build rule for target.
TEST_reloadShaders: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 TEST_reloadShaders
.PHONY : TEST_reloadShaders

# fast build rule for target.
TEST_reloadShaders/fast:
	$(MAKE) -f tests\CMakeFiles\TEST_reloadShaders.dir\build.make tests/CMakeFiles/TEST_reloadShaders.dir/build
.PHONY : TEST_reloadShaders/fast

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... glimac
	@echo ... glcustom
	@echo ... fastnoise
	@echo ... barrenLands
	@echo ... TEST_createMapBiomeTexture
	@echo ... TEST_lightNormal
	@echo ... TEST_lightWithCam
	@echo ... TEST_moveCamera
	@echo ... TEST_reloadShaders
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

